services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: authentication
    ports:
      - "8079:8079"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/authentication-service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=Postgres_9
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres-auth
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres_9
      POSTGRES_DB: authentication-service
    ports:
      - "5429:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
